name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags in githhub

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Allow the token to create releases

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false